---
- name: Ensure {{site}} directory permission for webserver
  file:
    path: /var/www/html/{{site}}
    owner: www-data
    group: www-data
    mode: "0755"
    recurse: yes

- name: Ensure {{site}} file exists for nginx
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/sites-available/{{site}}
    mode: "0644"
  vars:
    enable_ssl: false
    domain_name: "{{site}}"

- name: Enable {{site}} nginx config
  file:
    src: /etc/nginx/sites-available/{{site}}
    dest: /etc/nginx/sites-enabled/{{site}}
    state: link
  notify: Restart nginx

- name: Flush all handlers at this point
  meta: flush_handlers

- name: Create and Install SSL Cert for {{site}}
  command: "certbot --nginx -d  {{ site }} -m {{ ng_certbot_mail_address }} --agree-tos --noninteractive --redirect"
  when: static_sites_enable_ssl

- name: Copy {{site}} https nginx config
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/sites-available/{{site}}
    mode: "0644"
  vars:
    enable_ssl: "{{static_sites_enable_ssl}}"
    domain_name: "{{site}}"
  notify:
    - Restart nginx
  when: static_sites_enable_ssl
