---
- name: Add MariaDB repository key
  apt_key:
    url: https://mariadb.org/mariadb_release_signing_key.asc
    keyring: /etc/apt/trusted.gpg.d/mariadb.gpg
    state: present

- name: Add official MariaDB {{mariadb_version}} ubuntu {{ ansible_distribution_release }} repository
  apt_repository:
    repo: "deb [arch=amd64,arm64 signed-by=/etc/apt/trusted.gpg.d/mariadb.gpg] https://dlm.mariadb.com/repo/mariadb-server/{{mariadb_version}}/repo/ubuntu {{ ansible_distribution_release }} main"
    state: present

- name: Install MariaDB dependencies
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - mariadb-server
    - python3-mysqldb

- name: Start MariaDB Service
  service:
    name: mariadb
    state: started
    enabled: yes

- name: Allow MariaDB to connect remotely
  lineinfile:
    path: "/etc/mysql/mysql.conf.d/mysqld.cnf"
    regexp: "^bind-address(.*)$"
    line: "#bind-address	= 127.0.0.1"
  when: mariadb_allow_remote_connection
  notify:
    - Restart MariaDB

- name: Update MariaDB root password for all host
  mysql_user:
    name: root
    host: "{{ item }}"
    password: "{{ mariadb_root_password }}"
    priv: "*.*:ALL,GRANT"
    login_user: root
    login_password: "{{ mariadb_root_password }}"
  with_items:
    - 127.0.0.1
    - localhost
    - "{{ (mariadb_allow_remote_connection) | ternary('%','::1') }}"

- name: Ensure anonymous users are not in the database
  mysql_user:
    name: ""
    host: localhost
    state: absent
    login_user: root
    login_password: "{{ mariadb_root_password }}"

- name: Remove test database
  mysql_db:
    name: test
    state: absent
    login_user: root
    login_password: "{{ mariadb_root_password }}"

- name: Create users
  mysql_user:
    name: "{{ item.value.user }}"
    password: "{{ item.value.pass }}"
    host: "{{ (mariadb_allow_remote_connection) | ternary('%','localhost') }}"
    login_user: root
    login_password: "{{ mariadb_root_password }}"
    state: present
  loop: "{{ lookup('ansible.builtin.dict', mariadb_users, wantlist=True) }}"
  loop_control:
    label: "{{item.key}}"
  when: mariadb_users is defined
  tags: create-users

- name: Create databases
  mysql_db:
    name: "{{item.key}}"
    state: present
    login_user: root
    login_password: "{{ mariadb_root_password }}"
  loop: "{{ lookup('ansible.builtin.dict', mariadb_databases, wantlist=True) }}"
  loop_control:
    label: "{{item.key}}"
  when: mariadb_databases is defined
  tags: create-databases

- name: Give perssion to users on some databases
  mysql_user:
    name: "{{item.value}}"
    append_privs: true
    priv: "{{item.key}}.*:ALL"
    login_user: root
    login_password: "{{ mariadb_root_password }}"
  loop: "{{ lookup('ansible.builtin.dict', mariadb_databases, wantlist=True) }}"
  loop_control:
    label: "{{item.key}}"
  when: mariadb_databases is defined
  tags: create-databases

- name: Flush all handlers at this point
  meta: flush_handlers
