---
# defaults file for vaultwarden
vaultwarden_version: 1.25.2
vaultwarden_db_type: postgresql
vaultwarden_db_host: db
vaultwarden_db_port: 5432
vaultwarden_db_user: nobody
vaultwarden_db_password: setme
vaultwarden_db_name: vaultwarden
vaultwarden_database_url: "{{vaultwarden_db_type}}://{{vaultwarden_db_user}}:{{vaultwarden_db_password}}@{{vaultwarden_db_host}}:{{vaultwarden_db_port}}/{{vaultwarden_db_name}}"
vaultwarden_db_max_connection: 3
vaultwarden_port: 8920
vaultwarden_websocket_enabled: "true"
vaultwarden_websocket_port: 30122
vaultwarden_sends_enabled: "false"
vaultwarden_emergency_access_allowed: "true"
vaultwarden_signups_allowed: "true"
vaultwarden_signups_verify: "true"
vaultwarden_domain: setme
vaultwarden_smtp_host: setme
vaultwarden_smtp_port: 587
vaultwarden_smtp_ssl: "starttls"
vaultwarden_smtp_timeout: 15
vaultwarden_smtp_from: setme
vaultwarden_smtp_from_name: Vault
vaultwarden_smtp_username: setme
vaultwarden_smtp_password: setme
