---
# tasks file for php
- name: Adding PHP PPA
  apt_repository:
    repo: "ppa:ondrej/php"
    state: present

- name: "Installing PHP {{php_version}}"
  apt:
    name: "php{{php_version}}"
    update_cache: true
    state: latest

- name: "Installing PHP {{php_version}} fpm"
  apt:
    name: "php{{php_version}}-fpm"
    state: latest
  when: php_install_fpm

- name: "Restart php{{php_version}}-fpm"
  service:
    name: "php{{php_version}}-fpm"
    state: restarted
  when: php_install_fpm

- name: "Installing PHP {{php_version}} extra packages"
  apt:
    name: "{{ [prefix] | product(php_extra_packages) | map('join')}}"
    update_cache: true
    state: latest
  vars:
    prefix: "php{{php_version}}-"

- name: "Removing libapache2-mod-php{{php_version}}"
  apt:
    name: "libapache2-mod-php{{php_version}}"
    update_cache: true
    state: absent
  when: php_install_fpm

- name: Delete old composer
  file:
    path: /usr/local/bin/composer
    state: absent
  when: php_update_composer

- name: Installing composer
  shell: curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
  args:
    creates: /usr/local/bin/composer

- block:
    - name: "Removing PHP version {{php_remove_old_version}}"
      apt:
        name: "php{{php_remove_old_version}}"
        state: absent
    - name: "Removing PHP {{php_remove_old_version}} extra packages"
      apt:
        name: "{{ [prefix] | product(php_extra_packages) | map('join')}}"
        update_cache: true
        state: absent
      vars:
        prefix: "php{{php_remove_old_version}}-"
  when: php_remove_old_version != ""
