galaxy_info:
  author: H.R. Shadhin
  description: Setup Firefly III personal finance management application
  company: ShanixLab

  license: GPL-3.0-or-later

  min_ansible_version: 2.1

  platforms:
    - name: Debian
      versions:
        - all
    - name: Ubuntu
      versions:
        - all

  galaxy_tags:
    - fire fly III
    - finance management
    - budgets

dependencies: []
