---
- name: Check zsh version
  shell: "set -o pipefail; zsh --version | cut -d ' ' -f2"
  args:
    executable: /bin/bash
  register: zsh_register_version
  check_mode: no
  changed_when: false
  tags: configure

- name: Set zsh_version variable
  set_fact:
    zsh_version: "{{ zsh_register_version.stdout }}"

- name: Check antigen version
  shell: |
    set -o pipefail
    cat "{{ zsh_antigen_path }}/antigen/VERSION" | tr -d 'v'
  args:
    executable: /bin/bash
  register: zsh_register_antigen_version
  changed_when: false
  failed_when: false
  check_mode: no
  tags: configure

- name: Set zsh_antigen_installed_version variable
  set_fact:
    zsh_antigen_installed_version: "{{ zsh_register_antigen_version.stdout }}"

- name: Write .zshrc config
  template:
    src: zshrc.j2
    dest: "{{ zsh_config }}"
    owner: "{{ zsh_user }}"
    group: "{{ zsh_user_group }}"

- name: Set zsh as default shell
  become: yes
  user:
    name: "{{ zsh_user }}"
    shell: /bin/zsh

- name: Add skip_global_compinit for disable early compinit call in Ubuntu
  become: yes
  lineinfile:
    regexp: "skip_global_compinit=1"
    line: "skip_global_compinit=1"
    dest: /etc/zsh/zshenv
    state: present
  when: ansible_distribution == 'Ubuntu'
