---
# tasks file for zsh
- block:
    - name: Run whoami without become
      command: whoami
      changed_when: false
      register: whoami

    - name: Set zsh_user as login user
      set_fact:
        zsh_user: "{{ whoami.stdout }}"

    - include_tasks: install.yml
      tags: [zsh, install]

    - include_tasks: configure.yml
      tags: [zsh, configure]

    - include_tasks: post-install.yml
      tags: [zsh, install, post_install]
  become: false

- name: Reset antigen cache
  command: "/bin/zsh -c 'source {{ zsh_config }}; antigen reset'"
  become: yes
  become_user: "{{ zsh_user }}"
  changed_when: false
  failed_when: false
  tags: always
