---
- name: Generate User Password file
  shell: python files/password_hasher.py {{ secondary_user_password }} > {{ user_passfile }}
  args:
    chdir: "{{role_path}}"
    creates: "{{ user_passfile }}"
  delegate_to: localhost
  become: no
  when: secondary_user_password | default('', true) | trim != ''

- name: create {{secondary_user_username}} group
  group:
    name: "{{secondary_user_username}}"
    state: present

- name: Ensure User {{secondary_user_username}} is Present
  user: name={{secondary_user_username}} password={{ lookup('file', user_passfile) }} groups=sudo,{{secondary_user_username}} shell="/bin/bash" state=present append=yes
  when: secondary_user_password | default('', true) | trim != ''

- name: Ensure User {{secondary_user_username}} is Present(no password)
  user: name={{secondary_user_username}} groups=sudo,{{secondary_user_username}} shell="/bin/bash" state=present append=yes
  when: secondary_user_password | default('', true) | trim == ''

- name: Add User to SUDOERS
  copy:
    dest: "/etc/sudoers.d/{{secondary_user_username}}"
    content: "{{secondary_user_username}} ALL=(ALL) NOPASSWD:ALL"

- name: Deploy SSH Key
  authorized_key: user={{secondary_user_username}} key="{{ lookup('file', ssh_pub_key_path) }}" state=present
