galaxy_info:
  author: H.R. Shadhin
  description: setup invidious server
  company: ShanixLab

  license: GPL-3.0-or-later

  min_ansible_version: 2.1

  platforms:
    - name: Debian
      versions:
        - all
    - name: Ubuntu
      versions:
        - all

  galaxy_tags:
    - invidious
    - youtube
    - video

dependencies: []
