---
# tasks file for searx
- name: Copy settings.yml file
  template:
    src: settings.yml.j2
    dest: "/var/www/html/{{searx_domain}}/settings.yml"
    mode: "0644"

- name: "Copy docker-compose"
  template:
    src: docker-compose.yaml.j2
    dest: "/var/www/html/{{searx_domain}}/docker-compose.yaml"
    mode: "0644"
  notify:
    - Restart searx

- name: Ensure {{searx_domain}} file exists for nginx
  template:
    src: nginx_http.conf.j2
    dest: /etc/nginx/sites-available/{{searx_domain}}
    mode: "0644"

- name: Enable {{searx_domain}} nginx config
  file:
    src: /etc/nginx/sites-available/{{searx_domain}}
    dest: /etc/nginx/sites-enabled/{{searx_domain}}
    state: link
  notify: Restart nginx

- name: Flush all handlers at this point
  meta: flush_handlers

- name: Create and Install Cert Using {{ certbot_plugin }} Plugin for {{searx_domain}}
  command: "certbot --{{ certbot_plugin }} -d  {{ searx_domain }} -m {{ certbot_mail_address }} --agree-tos --noninteractive --redirect"
  when: is_local is defined and not is_local

- name: Copy nginx config
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/sites-available/{{searx_domain}}
    mode: "0644"
  when: is_local is defined and not is_local
  notify:
    - Restart nginx

- name: Create searx systemd service unit
  template:
    src: searx.service.j2
    dest: /etc/systemd/system/searx.service
    owner: root
    group: root
    mode: "0644"
  notify:
    - Restart searx

- name: Flush all handlers at this point
  meta: flush_handlers
