---
- hosts: POSTBOX
  name: Provision postbox(s)
  gather_facts: true
  become: true
  vars_files:
    - vars/default.yml
  vars:
    - ng_primary_domain: "{{mail_domain}}"
  roles:
    # - base
    # - zsh
    # - docker
    - nginx
    # - mailbox # incomplete
