---
- hosts: VPS
  name: Provision VPS(s)
  gather_facts: true
  become: true
  vars_files:
    - vars/default.yml
  roles:
    # - base
    # - zsh
    # - docker
    # - postgresql
    # - mariadb
    # - redis
    # - nginx
    # - php
    # - websites
    # - vaultwarden
    # - shiori
    # - firefly3
    # - dnote
    # - focalboard
    # - monica
    # - searx
    # - invidious
    # - backup
    # - blocky
    # - wireguard
    # - monitoring
    - owntracks

  tasks:
    - name: Setup ad-block list update hosts git automation
      ansible.builtin.include_tasks: tasks/hosts-git.yml
      when: setup_hosts_git

    - name: WOW
      ansible.builtin.debug:
        msg: "Playbook Completed"
