---
- hosts: VPS
  name: Provision VPS(s)
  gather_facts: yes
  become: yes
  vars_files:
    - vars/default.yml
  roles:
    - base
    - zsh
    - docker
    - postgresql
    - mariadb
    - redis
    - nginx
    - php
    - websites
    - vaultwarden
    - shiori
    - firefly3
    - dnote
    - focalboard
    - monica
    - searx
    - invidious
    - backup
    - blocky
    - wireguard
    - monitoring

  tasks:
    - name: WOW
      debug:
        msg: "Playbook Completed"
