galaxy_info:
  author: H.R. Shadhin
  description: Backup VPS necessary files

  license: GPL-3.0-or-later

  min_ansible_version: 2.1

  platforms:
    - name: Debian
      versions:
        - all
    - name: Ubuntu
      versions:
        - all

  galaxy_tags:
    - backups
    - app backup
    - db backup

dependencies: []
