---
# defaults file for base
sysadmin_email: devops@example.com
add_swap: false
swap_space: 512M
time_zone: Asia/Dhaka
add_secondary_user: false
secondary_user_username: devops
secondary_user_password: Super7secre8
user_passfile: .password.hash
ssh_port: 22
ssh_pub_key_path: ~/.ssh/id_rsa.pub
is_install_fail2ban: False
is_install_ufw: False

ufw_rules: []
