- block:
    - name: Create Wireguard user config directory
      file:
        path: "{{ wg_conf_dir }}/{{ item.value.username }}"
        state: directory
      with_dict: "{{ wg_user_list }}"
      loop_control:
        label: "{{ item.value.username }}"
      when: (item.value.remove == False)

    - name: Remove Wireguard user config directory
      file:
        path: "{{ wg_conf_dir }}/{{ item.value.username }}"
        state: absent
      with_dict: "{{ wg_user_list }}"
      loop_control:
        label: "{{ item.value.username }}"
      when: (item.value.remove == True)

    - name: Generate Wireguard users key
      shell: |
        if [ ! -f {{ wg_conf_dir }}/{{ item.value.username }}/privatekey ]
          then
            cd {{ wg_conf_dir }}/{{ item.value.username }}
            wg genkey | tee privatekey | wg pubkey > publickey
        fi 
        exit 0
      with_dict: "{{ wg_user_list }}"
      loop_control:
        label: "{{ item.value.username }}"
      when: (item.value.remove == False)

    - name: Read user public key
      slurp:
        src: "{{ wg_conf_dir }}/{{ item.value.username }}/publickey"
      with_dict: "{{ wg_user_list }}"
      loop_control:
        label: "{{ item.value.username }}"
      register: wg_user_publickey
      when: (item.value.remove == False)

    - name: Read user private key
      slurp:
        src: "{{ wg_conf_dir }}/{{ item.value.username }}/privatekey"
      with_dict: "{{ wg_user_list }}"
      loop_control:
        label: "{{ item.value.username }}"
      register: wg_user_privatekey
      when: (item.value.remove == False)
  tags: wg-config
