---
# tasks file for firefly3
- name: Install dependency packages
  apt:
    name: language-pack-nl-base

- name: Generate locale
  shell: locale-gen

- name: "Ensure {{firefly3_domain}} directory exists"
  file:
    path: "/var/www/html/{{firefly3_domain}}"
    owner: www-data
    group: www-data
    mode: "0755"
    state: directory
    recurse: true

- name: Check if fire fly iii already exists.
  stat:
    path: "/var/www/html/{{firefly3_domain}}/composer.json"
  register: firefly3_composer_json

- name: Install fire fly III
  become_user: www-data
  composer:
    command: create-project
    arguments: "grumpydictator/firefly-iii . {{firefly3_version}}"
    working_dir: "/var/www/html/{{firefly3_domain}}"
    prefer_dist: yes
  when: not firefly3_composer_json.stat.exists

- name: Copy .env file
  template:
    src: .env.j2
    dest: "/var/www/html/{{firefly3_domain}}/.env"
    mode: "0644"

- name: Create robots.txt
  copy:
    content: "User-agent: *\nDisallow: /\n"
    dest: "/var/www/html/{{firefly3_domain}}/robots.txt"

- name: Upgrade DB changes
  shell: php artisan firefly-iii:upgrade-database
  args:
    chdir: "/var/www/html/{{firefly3_domain}}"

- name: Ensure {{firefly3_domain}} file exists for nginx
  template:
    src: nginx_http.conf.j2
    dest: /etc/nginx/sites-available/{{firefly3_domain}}
    mode: "0644"
  notify: Restart nginx

- name: Enable {{firefly3_domain}} nginx config
  file:
    src: /etc/nginx/sites-available/{{firefly3_domain}}
    dest: /etc/nginx/sites-enabled/{{firefly3_domain}}
    state: link
  notify: Restart nginx

- name: Create and Install Cert Using {{ certbot_plugin }} Plugin for {{firefly3_domain}}
  command: "certbot --{{ certbot_plugin }} -d  {{ firefly3_domain }} -m {{ certbot_mail_address }} --agree-tos --noninteractive --redirect"
  when: is_local is defined and not is_local

- name: Copy nginx config
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/sites-available/{{firefly3_domain}}
    mode: "0644"
  when: is_local is defined and not is_local
  notify:
    - Restart nginx

- name: Flush all handlers at this point
  meta: flush_handlers
