---
# handlers file for owntracks
- name: Restart owntracks_server
  systemd:
    daemon_reload: true
    enabled: true
    name: owntracks_server
    state: restarted

- name: Restart nginx
  service:
    name: nginx
    state: restarted
